---
title: "An Empirical Study on Deep Neural Network Models for Chinese Dialogue Generation"
collection: 
permalink: /publication/2020_symmetry_ch_dialogue
excerpt: ''
date: 2020-10-23
author: Zhe Li*, <b>Mieradilijiang Maimaiti</b>*, Jiabao Sheng, Zunwang Ke, Wushour Slamu†, Qinyong Wang, and Xiuhong Li
conference: In Symmetry-Basel <b>(2020)</b> (*=equal contribution, †=corresponding author)
venue: ''
paperurl: 'https://www.mdpi.com/2073-8994/12/11/1756'
citation: '<br>
@inproceedings{zheli2020_chinese_dialogue,<br>
  title={An Empirical Study on Deep Neural Network Models for Chinese Dialogue Generation},<br>
  author={Zhe Li, Mieradilijiang Maimaiti, Jiabao Sheng, Zunwang Ke, Wushour Slamu, Qinyong Wang, Xiuhong Li},<br>
  booktitle={Symmetry-Basel},<br>
  year={2020},<br>
}'


---
<h2><strong>Abstract</strong></h2>
The task of dialogue generation has attracted increasing attention due to its diverse downstream applications, such as question-answering systems and chatbots. 
Recently, the deep neural network (DNN)-based dialogue generation models have achieved superior performance against conventional models utilizing statistical machine learning methods. 
However, despite that an enormous number of state-of-the-art DNN-based models have been proposed, there lacks detailed empirical comparative analysis for them on the open Chinese corpus. 
As a result, relevant researchers and engineers might find it hard to get an intuitive understanding of the current research progress. 
To address this challenge, we conducted an empirical study for state-of-the-art DNN-based dialogue generation models in various Chinese corpora. 
Specifically, extensive experiments were performed on several well-known single-turn and multi-turn dialogue corpora, including KdConv, Weibo, and Douban, 
to evaluate a wide range of dialogue generation models that are based on the symmetrical architecture of Seq2Seq, RNNSearch, transformer, generative adversarial nets, and reinforcement learning respectively. 
Moreover, we paid special attention to the prevalent pre-trained model for the quality of dialogue generation. 
Their performances were evaluated by four widely-used metrics in this area: BLEU, pseudo, distinct, and rouge. 
Finally, we report a case study to show example responses generated by these models separately.

\[[PDF](https://www.mdpi.com/2073-8994/12/11/1756)\]
